GET http://localhost:3001/api/users/

###
GET http://localhost:3001/api/blogs/

### 
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"Zoro",
    "name":"Roronoa Zoro",
    "password": "sword"
}

### 
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"Zoro",
    "password": "sword"
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ilpvcm8iLCJpZCI6IjVmM2Q0Nzc5Y2Q1NzI5NWE0YzYyYjU0ZSIsImlhdCI6MTU5ODIwOTc3NH0.iWczRejaRAss1mNc9hXP28yMYFChlmrUgdZNYZtdUbE

{
    "title":"the vegeS  ",
   "author":"hectsdosr",
    "url": "www.senk.ed",
    "likes":211
}

### 
DELETE http://localhost:3001/api/blogs/5f3c21cc216ac85b102aff9d
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ilpvcm8iLCJpZCI6IjVmM2Q0Nzc5Y2Q1NzI5NWE0YzYyYjU0ZSIsImlhdCI6MTU5Nzg1MTU0MH0.kkOk463auEAEtB1Yq4LB91IlPwP4L9onmchqyIoWdek
